### ISSUE TITLE
Timezone offset does not match system offset - check your config files

### ISSUE THREAD

**Issue by xeruf** [JensErat/task-relative-recur#17]
```sh
Traceback (most recent call last):
  File "/home/janek/.local/share/task/hooks/on-add-pirate", line 9, in <module>
    from tasklib import TaskWarrior, Task
  File "/usr/local/lib/python3.8/dist-packages/tasklib/__init__.py", line 1, in <module>
    from .backends import TaskWarrior
  File "/usr/local/lib/python3.8/dist-packages/tasklib/backends.py", line 11, in <module>
    from .task import Task, TaskQuerySet, ReadOnlyDictView
  File "/usr/local/lib/python3.8/dist-packages/tasklib/task.py", line 9, in <module>
    from .serializing import SerializingObject
  File "/usr/local/lib/python3.8/dist-packages/tasklib/serializing.py", line 11, in <module>
    local_zone = tzlocal.get_localzone()
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 7200 != 0. Please, check your config files.
Hook Error: Expected feedback from a failing hook script.
```

I am a developer, but I rarely use python, so idk what I'm supposed to do with this. The hook shouldn't care about my system time at all?
I live in Germany (CEST) btw.

**Comment by xeruf** [comment]
Oh wait, looks like this isn't even your hooks fault...

**Comment by xeruf** [comment]
Moved to https://github.com/robgolding/tasklib/issues/84

**Comment by xeruf** [comment]
Nevermind, the issue is in this project:
```sh
env = os.environ.copy()
env['TZ'] = 'UTC0'
```
WHYYYYYYYYY?

This caused me over an hour of debugging just now :/

**Comment by Alys** [comment]
I had the same issue with `on-add-pirate` after installing `task-relative-recur`, and found that commenting out that env['TZ'] line did fix it.

I haven't noticed any incorrect behaviour from `task-relative-recur` since then although I'm not certain what impacts using something other than UTC0 would have. If UTC0 is useful or necessary in some circumstances, maybe it's worth mentioning in the README that you could comment out or adjust the timezone if needed?

I know that for my own use of this hook, I wouldn't care if the new tasks weren't due on exactly the right days due to a time zone issue.

https://github.com/JensErat/task-relative-recur/blob/161e1a9e2605c256e56f4aaf494e2041008d8b57/on-modify.relative-recur#L20
